### PR TITLE
Update ticket.php

### PR DESCRIPTION
**Pull request by Baptistecottey**
Correct syntax error

### CODE REVIEW

**Comment by jshah4517** [comment]
Thanks @Baptistecottey - do you think you might have more changes? I can wait to merge until you've completed reviewing the files.

**Comment by Baptistecottey** [comment]
Hi @jshah4517 

Yes i found other typos mistake.

Please wait beforge merge, i'll ping you when you can merge 😊

**Comment by Baptistecottey** [comment]
Hi @jshah4517 

I've made several translations and correction.

Please could you merge the PR ?

**Comment by jshah4517** [comment]
Thank you @Baptistecottey

**Pull request merged**
