### PR TITLE
Updated russian translation for version 3.4.*

### PR DESCRIPTION
**Pull request by a-shkarlatov**
Updated Russian translation for version 3.4.*

### CODE REVIEW

**Review by bytestream — CHANGES_REQUESTED** [review]
Thanks for your efforts on this @shlarlatov !

Please could you revert the indentation / spacing changes around the `=>` characters.

**Comment by shlarlatov** [comment]
I can’t, sry = (  I have auto-formatting configured on save, and i didn't save a copy without this indentation / spacing changes =(

**Review by bytestream — APPROVED** [review]
I didn't realise some of the files were badly indented when I first checked. I've reverted some of the indentation changes which differ against the en/ files but there's still a lot which you've corrected.

Thanks for your help! :+1:

**Comment by a-shkarlatov** [comment]
Thanks you!=)

**Pull request merged**
